# Generated by Django 3.0 on 2019-12-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('byCar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='商务车', max_length=100)),
                ('c_number', models.CharField(default=0, max_length=100)),
                ('c_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanForCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=18)),
                ('p_do', models.CharField(max_length=500)),
                ('p_time_begin', models.DateTimeField()),
                ('p_time_end', models.DateTimeField()),
                ('p_time_create', models.DateTimeField(auto_now_add=True)),
                ('p_time_change', models.DateTimeField(auto_now=True)),
                ('p_status', models.BooleanField(default=True)),
                ('p_car', models.CharField(max_length=200)),
            ],
        ),
    ]
